dist: xenial
addons:
  hosts:
    - iemdb-talltowers.local
language: python
python:
  - "3.6"
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -qq
  # https://travis-ci.community/t/install-postgresql-11/3894/5
  - sudo service postgresql stop
  - sudo apt-get --yes remove postgresql-10-postgis-2.4
  - sudo apt install -yq --no-install-suggests --no-install-recommends postgresql-11-postgis-2.5-scripts postgresql-11 postgresql-client-11 postgresql-11-postgis-2.5
  - sed -e 's/^port.*/port = 5432/' /etc/postgresql/11/main/postgresql.conf > postgresql.conf
  - sudo chown postgres postgresql.conf
  - sudo cp /etc/postgresql/{10,11}/main/pg_hba.conf
  - sudo mv postgresql.conf /etc/postgresql/11/main
  - sudo service postgresql restart 11

install:
  - "pip install --upgrade pip"
  - "pip install pandas psycopg2 pytz"
before_script:
  - cat config/settings-in.json |  sed -e "s,{{path}},`pwd`,g" | tee config/settings.json > /dev/null
  - cd database; sh bootstrap.sh
  - cd ..
script:
  - cd csi2pg; nosetests test_csi2pg.py
