dist: bionic
addons:
  hosts:
    - iemdb-talltowers.local
language: python
python:
  - "3.8"

before_install:
  - cat config/settings-in.json |  sed -e "s,{{path}},`pwd`,g" | tee config/settings.json > /dev/null
  - git clone --depth 1 https://github.com/akrherz/iem-database.git iemdatabase
  - git clone --depth 1 https://github.com/akrherz/ci_tooling.git .ci_tooling
  - . .ci_tooling/postgres.sh

install:
  - "pip install --upgrade pip"
  - "pip install pandas psycopg2 pytz"

before_script:
  # https://travis-ci.community/t/t/712/12
  - export PATH="/usr/lib/postgresql/11/bin:$PATH"
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres || true
  - cd database; sh bootstrap.sh
  - python schema_manager.py
  - cd ..

script:
  - cd csi2pg; nosetests test_csi2pg.py
