sudo: required
dist: trusty
addons:
  hosts:
    - iemdb
virtualenv:
  system_site_packages: true
language: python
python:
  - "2.7"
before_install:
  - chmod 755 $HOME
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-psycopg2
install:
  - "pip install --upgrade pip"
before_script:
  - cat config/settings-in.json |  sed -e "s,{{path}},`pwd`,g" | tee config/settings.json > /dev/null
  - cd database; sh bootstrap.sh
  - cd ..
script:
  - cd csi2pg; nosetests test_csi2pg.py
